### ISSUE TITLE
How to edit sass variables? Where is the _settings file located?

### ISSUE THREAD

**Issue by devinrhode2** [acoustep/ember-cli-foundation-6-sass#2]
1. Where is the _settings and other foundation files located? For now I'm referencing https://github.com/zurb/foundation-sites/blob/v6.0.3/scss/settings/_settings.scss

2. What is the best way to customize the sass variables? For now I'm putting my variables above the foundation import statements in app.scss. This seems to work and has the added benefit of allowing me to update foundation (and it's default settings) without having my custom settings overwritten.

**Comment by acoustep** [comment]
Hi devinhode2,

1.  All foundation files are downloaded with NPM.  So they are all stored in the ```node_modules/foundation-sites``` directory. Because of this, I recommend not editing them as they will be overwritten when updating (As you say in your second point).

2. Yes, as far as I'm aware that's the best method. If there are a lot of settings to change I usually create a new file e.g. ```_foundation-overrides.scss``` in my stylesheets directory and import it above foundation in the ```app.scss```.

Hope that helps!

**Comment by acoustep** [comment]
Closing this for now. Feel free to reopen if you're still having issues!
