### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by williamweckl** [acoustep/ember-cli-foundation-6-sass#30]
How do I install this addon?

Tried `ember install ember-cli-foundation-6-sass`.

output:

```
Error: Cannot find module '/home/william/dev/ember-project/node_modules/ember-cli-foundation-6-sass/bower.json'
```

Tried `npm install ember-cli-foundation-6-sass --save-dev`. It installed but if I try to use `ember g ember-cli-foundation-6-sass` the output is the same as the above one.

What am I missing? Should not this be documented?

**Comment by williamweckl** [comment]
Had to create bower.json file at node_modules/ember-cli-foundation-6-saas folder.

Created like this:
```
{
  "name": "ember-cli-foundation-6-sass",
  "dependencies": {
    "ember": "2.6.0",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-load-initializers": "0.1.7",
    "ember-qunit": "0.4.16",
    "ember-qunit-notifications": "0.1.0",
    "ember-resolver": "~0.1.20",
    "foundation-sites": "^6.0.3",
    "jquery": "~2.1.4",
    "loader.js": "ember-cli/loader.js#3.4.0",
    "qunit": "~1.20.0"
  },
  "resolutions": {
    "jquery": "~2.1.4"
  }
}
```

Can you verify why the npm version is comming without it?

**Comment by acoustep** [comment]
This is not intended, but I've just tested a fresh install and I'm getting the same issue.

Seems the issue is coming from between version 0.9 and 0.10, potentially to do with this commit https://github.com/acoustep/ember-cli-foundation-6-sass/commit/7d2dde612a78736e78982545462f3c565e3035d6 - although I'm not 100% sure. Still investigating.

A working (but outdated) version can be installed with 

ember install ember-cli-foundation-6-sass@0.0.9

**Comment by williamweckl** [comment]
@acoustep Thank you for the reply. Is there any launching date for the next version yet?

**Comment by acoustep** [comment]
This has now been fixed https://github.com/acoustep/ember-cli-foundation-6-sass/pull/31

**Comment by williamweckl** [comment]
@acoustep Thank you!
