### ISSUE TITLE
Failed to import util/util on ember 2.10

### ISSUE THREAD

**Issue by saski** [acoustep/ember-cli-foundation-6-sass#48]
I've set a new ember 2.10.0 project and after installing ember-cli-foundation-6-sass 0.18 I got
a SassCompiler compiling error when it tries to  `@import "util/util";`
Full error trace is on `ember serve` is:
```
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
File: /Users/nachosaski/workspace/ember-vers/tmp/sass_compiler-input_base_path-74l93EFP.tmp/0/app/styles/_settings.scss (44)
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: util/util.
Parent style sheet: /Users/nachosaski/workspace/ember-vers/tmp/sass_compiler-input_base_path-74l93EFP.tmp/0/app/styles/_settings.scss
    at options.error (/Users/nachosaski/workspace/ember-vers/node_modules/node-sass/lib/index.js:286:26)
```

**Comment by ctcpip** [comment]
+1

**Comment by ctcpip** [comment]
looks related to #46 changes.  @GCheung55 can you advise, please?

**Comment by ctcpip** [comment]
@saski I was able to get it to run without error using this workaround:

- in app.scss change `@import 'foundation';` to `@import 'foundation-sites/foundation';`
- in _settings.scss change `@import 'util/util';` to `@import 'foundation-sites/util/util';`

**Comment by shicholas** [comment]
probably related to https://github.com/aexmachina/ember-cli-sass/issues/151

**Comment by GCheung55** [comment]
This is due to the change to support foundation-sites@6.3.0. Foundation-sites restructured their directories.

Prior to this change, all the sass/scss files from foundation-sites were included and could be imported globally.

In order to support this change, the Addon was updated load files in a way that required importing with 'foundation-sites/`.

Thus `@import "foundation-sites/util/util";`

**Comment by aexmachina** [comment]
Yes, Foundation's definitely thrown everyone a curve ball here. They rearranged their folder structure without bumping the major version.

**Comment by zhujy8833** [comment]
I was having the same issue when using `foundation-site 6.3.0` with `ember-cli 2.10`. I could workaround this `util/util` issue by putting this inside `ember-cli-build.js`.
```javascript
    var app = new EmberApp(defaults, {
    // Add options here
    sassOptions: {
      includePaths: [
        'bower_components/foundation-sites/scss'
      ]
    }
  });
``` 
Also, yeah, I need `@import 'foundation-sites/foundation'` instead of `@import 'foundation'`.
Should we update README file to include this change?

**Comment by GCheung55** [comment]
Adding path in sassOptions is kind of a bummer.

I think the README should be updated with something more substantial than the little comment I left in an example. Something more explicit for sure. @zhujy8833 care to put a PR together?

**Comment by zhujy8833** [comment]
@GCheung55 I have opened a PR to update README to have the right `@import`: https://github.com/acoustep/ember-cli-foundation-6-sass/pull/50
Please take a look :-)

**Comment by GCheung55** [comment]
@acoustep I think this can be closed now.
